export const allPlayers = [
    { name: "Ashkar", skill: "good" },
    { name: "Shamsu", skill: "best" },
    { name: "Hashir", skill: "average" },
    { name: "Fais", skill: "average" },
    { name: "Jamshi", skill: "average" },
    { name: "Jassim", skill: "average" },
    { name: "Rahees", skill: "average" },
    { name: "Rizwan", skill: "best" },
    { name: "Ichu", skill: "best" },
    { name: "Siraj", skill: "best" },
    { name: "Asif", skill: "good" },
    { name: "Ansar", skill: "average" },
    { name: "Ajmi", skill: "average" },
    { name: "Jarees", skill: "average" },
    { name: "Pachu", skill: "best" },
    { name: "Jappu", skill: "good" },
    { name: "Achu", skill: "average" },
    { name: "Raheem", skill: "average" },
    { name: "Jasil", skill: "good" },
    { name: "Noushik", skill: "good" },
    { name: "Noufi", skill: "good" },
    { name: "Rashi", skill: "good" },
    { name: "Umba", skill: "good" },

  ];